version: '3.8'
services:
  backend:
    build:
      context: ./api
    ports:
      - "4000:5000"
    env_file:
      - ./api/.env
    depends_on:
      - db
    
  frontend:
    build:
      context: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    

  