# Use the official Node.js image
FROM node:18

# Set the working directory
WORKDIR /api

# Copy package.json and package-lock.json to the /app directory
COPY package.json ./

# Install dependencies
RUN npm install 

# Copy the backend code
COPY . .

# Expose the backend port
EXPOSE 4000

# Start the app
CMD ["node", "index.js"]
